export const ESPECIE_OPTIONS = [
  { value: '1', label: '1 - Pensão por Morte de Trabalhador Rural' },
  { value: '2', label: '2 - Pensão por Morte Acidentária Trabalhador Rural' },
  { value: '3', label: '3 - Pensão por Morte de Empregador Rural' },
  { value: '4', label: '4 - Aposentadoria por Invalidez Trabalhador Rural' },
  { value: '5', label: '5 - Aposentadoria Invalidez Acidentária Trabalhador Rural' },
  { value: '6', label: '6 - Aposentadoria Invalidez Empregador Rural' },
  { value: '7', label: '7 - Aposentadoria por Velhice Trabalhador Rural' },
  { value: '8', label: '8 - Aposentadoria por Idade Empregador Rural' },
  { value: '9', label: '9 - Compl. Acidente Trabalho p/Trabalhador (rural)' },
  { value: '10', label: '10 - Auxílio Doenca Acidentário Trabalhador Rural' },
  { value: '11', label: '11 - Amparo Previdenc. Invalidez Trabalhador Rural' },
  { value: '12', label: '12 - Amparo Previdenc. Idade Trabalhador Rural' },
  { value: '13', label: '13 - Auxílio Doenca Trabalhador Rural' },
  { value: '15', label: '15 - Auxílio Reclusão Trabalhador Rural' },
  { value: '19', label: '19 - Pensão de Estudante (lei 7.004/82)' },
  { value: '20', label: '20 - Pensão por Morte de Ex Diplomata' },
  { value: '21', label: '21 - Pensão por Morte Previdenciária' },
  { value: '22', label: '22 - Pensão por Morte Estatutária' },
  { value: '23', label: '23 - Pensão por Morte de Ex Combatente' },
  { value: '24', label: '24 - Pensão Especial (ato Institucional)' },
  { value: '25', label: '25 - Auxílio Reclusão' },
  { value: '26', label: '26 - Pensão por Morte Especial' },
  { value: '27', label: '27 - Pensão Morte Servidor Público Federal' },
  { value: '28', label: '28 - Pensão por Morte Regime Geral' },
  { value: '29', label: '29 - Pensão por Morte Ex Combatente Maritimo' },
  { value: '30', label: '30 - Renda Mensal Vitalícia por Incapacidade' },
  { value: '31', label: '31 - Auxílio Doenca Previdenciário' },
  { value: '32', label: '32 - Aposentadoria Invalidez Previdenciária' },
  { value: '33', label: '33 - Aposentadoria Invalidez Aeronauta' },
  { value: '34', label: '34 - Aposentadoria Inval. Ex Combatente Marítimo' },
  { value: '35', label: '35 - Auxílio Doenca do Ex Combatente' },
  { value: '36', label: '36 - Auxílio Acidente Previdenciário' },
  { value: '37', label: '37 - Aposentadoria Extranumerário Capin' },
  { value: '38', label: '38 - Aposentadoria Extranum. Funcionário Público' },
  { value: '39', label: '39 - Auxílio Invalidez Estudante' },
  { value: '40', label: '40 - Renda Mensal Vitalícia por Idade' },
  { value: '41', label: '41 - Aposentadoria por Idade' },
  { value: '42', label: '42 - Aposentadoria por Tempo de Contribuição' },
  { value: '43', label: '43 - Aposentadoria por Tempo Serviço Ex Combatente' },
  { value: '44', label: '44 - Aposentadoria Especial de Aeronauta' },
  { value: '45', label: '45 - Aposentadoria Tempo Serviço Jornalista' },
  { value: '46', label: '46 - Aposentadoria Especial' },
  { value: '47', label: '47 - Abono Permanencia em Serviço 35 Anos' },
  { value: '48', label: '48 - Abono Permanencia em Serviço 30 Anos' },
  { value: '49', label: '49 - Aposentadoria Ordinária' },
  { value: '50', label: '50 - Auxílio Doenca Extinto Plano Básico' },
  { value: '51', label: '51 - Aposentadoria Invalidez Extinto Plano Básico' },
  { value: '52', label: '52 - Aposentadoria Idade Extinto Plano Básico' },
  { value: '53', label: '53 - Auxílio Reclusão Extinto Plano Básico' },
  { value: '54', label: '54 - Pensão Indenizatória a Cargo da União' },
  { value: '55', label: '55 - Pensão por Morte Extinto Plano Básico' },
  { value: '56', label: '56 - Pensão Vitalícia Sindrome Talidomida' },
  { value: '57', label: '57 - Aposentadoria Tempo de Serviço de Professor' },
  { value: '58', label: '58 - Aposentadoria de Anistiados' },
  { value: '59', label: '59 - Pensão por Morte de Anistiados' },
  { value: '60', label: '60 - Benefício Indenizatório a cargo da União' },
  { value: '61', label: '61 - Auxílio Natalidade' },
  { value: '62', label: '62 - Auxílio Funeral' },
  { value: '63', label: '63 - Auxílio Funeral Trabalhador Rural' },
  { value: '64', label: '64 - Auxílio Funeral Empregador Rural' },
  { value: '65', label: '65 - Pecúlio Especial Servidor Autarquico' },
  { value: '66', label: '66 - Pec. Esp. Servidor Autarquico' },
  { value: '67', label: '67 - Pecúlio Obrigatório Ex Ipase' },
  { value: '68', label: '68 - Pecúlio Especial de Aposentados' },
  { value: '69', label: '69 - Pecúlio de Estudante' },
  { value: '70', label: '70 - Restituicao Contrib. P/Seg. S/Carência' },
  { value: '71', label: '71 - Salario Familia Previdenciário' },
  { value: '72', label: '72 - Aposentadoria Tempo Serviço Lei de Guerra' },
  { value: '73', label: '73 - Salario Familia Estatutário' },
  { value: '74', label: '74 - Complemento de Pensão a Conta da União' },
  { value: '75', label: '75 - Complemento de Aposentadoria a Conta da União' },
  { value: '76', label: '76 - Salario Familia Estatutário' },
  { value: '77', label: '77 - Salario Fam. Estatutário Servidor Sinpas' },
  { value: '78', label: '78 - Aposentadoria Idade Lei de Guerra' },
  { value: '79', label: '79 - Vantagens de Servidor Aposentado' },
  { value: '80', label: '80 - Auxílio Salario Maternidade' },
  { value: '81', label: '81 - Aposentadoria Compulsoria Ex Sasse' },
  { value: '82', label: '82 - Aposentadoria Tempo de Serviço Ex Sasse' },
  { value: '83', label: '83 - Aposentadoria por Invalidez Ex Sasse' },
  { value: '84', label: '84 - Pensão por Morte Ex Sasse' },
  { value: '85', label: '85 - Pensão Vitalícia Seringueiros' },
  { value: '86', label: '86 - Pensão Vitalícia Dependentes Seringueiro' },
  { value: '87', label: '87 - Amp. Social Pessoa Portadora Deficiencia' },
  { value: '88', label: '88 - Amparo Social ao Idoso' },
  { value: '89', label: '89 - Pensão Esp. Vitimas Hemodiálise Caruaru' },
  { value: '90', label: '90 - Simples Assist. Médica p/ Acidente Trabalhador' },
  { value: '91', label: '91 - Auxílio Doenca por Acidente do Trabalho' },
  { value: '92', label: '92 - Aposentadoria Invalidez Acidente Trabalho' },
  { value: '93', label: '93 - Pensão por Morte Acidente do Trabalho' },
  { value: '94', label: '94 - Auxílio Acidente' },
  { value: '95', label: '95 - Auxílio Suplementar Acidente Trabalho' },
  { value: '96', label: '96 - Pensão Especial Hanseníase Lei 11520/07' },
  { value: '97', label: '97 - Pecúlio por Morte Acidente do Trabalho' },
  { value: '98', label: '98 - Abono Anual de Acidente de Trabalho' },
  { value: '99', label: '99 - Afastamento Até 15 Dias Acidente Trabalhador' }
];
